package application;

import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

import java.util.ArrayList;
import java.util.List;

import org.junit.Ignore;
import org.junit.Test;

import console.Console;

public class GameTest {

	@Test
	public void testGoThroughtFieldsForManualCreatedBoard() { // Tu problem !!
		List<Boolean> list = new ArrayList<Boolean>();
		for (int i = 0; i < 25; i++) {
			list.add(false);
		}
		list.remove(7);
		list.add(7, true); 

		list.remove(12);
		list.add(12, true);

		list.remove(17);
		list.add(17, true);

		Board board = new Board(5, 5, list);
		Console console = new Console(5, 5, board);
		Game game = new Game(console);
		try {
			game.goThroughtFields();
		} catch (EndOfGameException exc) {
			System.out.println(exc);
		}
		assertTrue(board.getBoardList().get(11).getLifeStatus()); 
		assertTrue(board.getBoardList().get(12).getLifeStatus());
		assertTrue(board.getBoardList().get(13).getLifeStatus());

	}

	@Ignore
	public void testGoThroughtFieldsForManualCreatedBoardWithException() {
		List<Boolean> list = new ArrayList<Boolean>();
		for (int i = 0; i < 9; i++) {
			list.add(false);
		}
		list.remove(0);
		list.add(0, true);

		Board board = new Board(3, 3, list);
		Console console = new Console(3, 3, board);
		Game game = new Game(console);
		try {
			game.goThroughtFields();
		} catch (EndOfGameException exc) {
			return;
		}
		fail("EndOfGameException shoul accure !");
	}

}
